### ISSUE TITLE
FlowRouterMeta is not a function

### ISSUE THREAD

**Issue by jalaux** [VeliovGroup/Meteor-flow-router-meta#10]
### I'm having an issue:
When i just install FlowRouterMeta 

```
import { FlowRouterMeta, FlowRouterTitle } from 'meteor/ostrio:flow-router-meta';
console.log(FlowRouterMeta);
new FlowRouterMeta(FlowRouter);
new FlowRouterTitle(FlowRouter
```

Got the following message ...
```

I20180613-16:31:04.849(2)? undefined          
W20180613-16:31:06.419(2)? (STDERR) /home/joel/.meteor/packages/meteor-tool/.1.5.2_2.irtbc9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180613-16:31:06.420(2)? (STDERR) 						throw(ex);
W20180613-16:31:06.420(2)? (STDERR) 						^
W20180613-16:31:06.421(2)? (STDERR) 
W20180613-16:31:06.421(2)? (STDERR) TypeError: FlowRouterMeta is not a function
W20180613-16:31:06.421(2)? (STDERR)     at meteorInstall.route.zzz_router.js (route/zzz_router.js:39:1)
W20180613-16:31:06.422(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20180613-16:31:06.422(2)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20180613-16:31:06.423(2)? (STDERR)     at /home/joel/project/c10po/beta/.meteor/local/build/programs/server/app/app.js:26001:1
W20180613-16:31:06.424(2)? (STDERR)     at /home/joel/project/c10po/beta/.meteor/local/build/programs/server/boot.js:339:34
W20180613-16:31:06.424(2)? (STDERR)     at Array.forEach (native)
W20180613-16:31:06.425(2)? (STDERR)     at Function._.each._.forEach (/home/joel/.meteor/packages/meteor-tool/.1.5.2_2.irtbc9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20180613-16:31:06.426(2)? (STDERR)     at /home/joel/project/c10po/beta/.meteor/local/build/programs/server/boot.js:158:5
W20180613-16:31:06.426(2)? (STDERR)     at /home/joel/project/c10po/beta/.meteor/local/build/programs/server/boot.js:388:5
W20180613-16:31:06.427(2)? (STDERR)     at Function.run (/home/joel/project/c10po/beta/.meteor/local/build/programs/server/profile.js:510:12)
W20180613-16:31:06.428(2)? (STDERR)     at /home/joel/project/c10po/beta/.meteor/local/build/programs/server/boot.js:387:11
```

I'm on ubuntu 16.04 and Meteor 1.5.4.2

**Comment by dr-dimitru** [comment]
Hey @jalaux ,

`{ FlowRouterMeta, FlowRouterTitle }` are *Client* only libs.
And I see you're getting errors at server.
You can simply wrap it into `Meteor.isClient` condition

**Comment by jalaux** [comment]
Great.
thanks

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/flow-router)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/flow-router-extra)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
